




/* 去掉优先级等标记，从错误码转换成资源ID */
#define ERROR_GET_RCID(errno)           ((errno) & 0x0FFFFFFF);

#define ERROR_SEVERITY_SUCCESS          0x0
#define ERROR_SEVERITY_INFO             0x1
#define ERROR_SEVERITY_WARNING          0x2
#define ERROR_SEVERITY_ERROR            0x3

#define ERROR_GET_MODULEFACILITY(ulMID) (((ulMID)>>16)&0xfff)

#define ERROR_DEFINE(sev, fac, code)    ((ULONG)(((ULONG)((sev)&3)<<29) | \
                                        ((ULONG)((fac)& 0x0FFF)<<16)    | \
                                        ((ULONG)((code)&0xFFFF))))

#define ERROR_GET_SEVERITY(errno)       (((ULONG)(errno)>>29)&3)
#define ERROR_GET_FACILITY(errno)       (((ULONG)(errno)>>16)&0x0FFF)
#define ERROR_GET_CODE(errno)           ((ULONG)(errno)&0xFFFF)

#define IS_SUCCED(errno)                ((((ULONG)(errno)>>29)&3) == ERROR_SEVERITY_SUCCESS)
#define IS_INFO(errno)                  ((((ULONG)(errno)>>29)&3) == ERROR_SEVERITY_INFO)
#define IS_WARNING(errno)               ((((ULONG)(errno)>>29)&3) == ERROR_SEVERITY_WARNING)
#define IS_ERROR(errno)                 ((((ULONG)(errno)>>29)&3) == ERROR_SEVERITY_ERROR)

#define ERROR_COMMON_FACILITY                 ERROR_GET_MODULEFACILITY(0x00010000UL)
/* Leopard的错误码0x00010000 (FacilityΪ0x001)开始
   公共错误码的FacilityΪ0x001,其他模块的错误码的Facilit从0x0002开始
*/

#define ERROR_SUCCESS                         0x0000UL
#define ERROR_FAILED                          ERROR_DEFINE(ERROR_SEVERITY_WARNING, ERROR_COMMON_FACILITY, 0x1UL)
#define ERROR_INVALID_PARAMETER               ERROR_DEFINE(ERROR_SEVERITY_INFO,    ERROR_COMMON_FACILITY, 0x2UL)
#define ERROR_BAD_STATE                       ERROR_DEFINE(ERROR_SEVERITY_ERROR,   ERROR_COMMON_FACILITY, 0x3UL)
#define ERROR_BAD_MSG                         ERROR_DEFINE(ERROR_SEVERITY_ERROR,   ERROR_COMMON_FACILITY, 0x4UL)
#define ERROR_NOT_FOUND                       ERROR_DEFINE(ERROR_SEVERITY_WARNING, ERROR_COMMON_FACILITY, 0x5UL)
#define ERROR_ALREADY_EXIST                   ERROR_DEFINE(ERROR_SEVERITY_WARNING, ERROR_COMMON_FACILITY, 0x6UL)
#define ERROR_ALREADY_TIMEOUT                 ERROR_DEFINE(ERROR_SEVERITY_WARNING, ERROR_COMMON_FACILITY, 0x7UL)
#define ERROR_ALREADY_NOTSUPPORT              ERROR_DEFINE(ERROR_SEVERITY_WARNING, ERROR_COMMON_FACILITY, 0x8UL)
#define ERROR_INCOMPLETE                      ERROR_DEFINE(ERROR_SEVERITY_WARNING, ERROR_COMMON_FACILITY, 0x9UL)
#define ERROR_NOT_INITIALIZED                 ERROR_DEFINE(ERROR_SEVERITY_WARNING, ERROR_COMMON_FACILITY, 0xAUL)
#define ERROR_NO_ENOUGH_RESOURCE              ERROR_DEFINE(ERROR_SEVERITY_WARNING, ERROR_COMMON_FACILITY, 0xBUL)
#define ERROR_VALUE_OUT_OF_RANGE              ERROR_DEFINE(ERROR_SEVERITY_INFO,    ERROR_COMMON_FACILITY, 0xCUL)
#define ERROR_INIT_ERROR                      ERROR_DEFINE(ERROR_SEVERITY_ERROR,   ERROR_COMMON_FACILITY, 0xDUL)
#define ERROR_NOT_READY                       ERROR_DEFINE(ERROR_SEVERITY_INFO,    ERROR_COMMON_FACILITY, 0xEUL)
#define ERROR_NO_ENOUGH_HARDWARE_RESOURCE     ERROR_DEFINE(ERROR_SEVERITY_WARNING, ERROR_COMMON_FACILITY, 0xFUL)
#define ERROR_RESOURCE_CONFLICT               ERROR_DEFINE(ERROR_SEVERITY_WARNING, ERROR_COMMON_FACILITY, 0x10UL)
#define ERROR_VLAN_NOTEXIST                   ERROR_DEFINE(ERROR_SEVERITY_ERROR,   ERROR_COMMON_FACILITY, 0x11UL)
#define ERROR_VLAN_NOTSTATIC                  ERROR_DEFINE(ERROR_SEVERITY_ERROR,   ERROR_COMMON_FACILITY, 0x12UL)
#define ERROR_VLAN_ISSUBVLAN                  ERROR_DEFINE(ERROR_SEVERITY_ERROR,   ERROR_COMMON_FACILITY, 0x13UL)
#define ERROR_VLAN_OVERFLOWLIMIT              ERROR_DEFINE(ERROR_SEVERITY_ERROR,   ERROR_COMMON_FACILITY, 0x14UL)
#define ERROR_VLAN_NOINTERFACE                ERROR_DEFINE(ERROR_SEVERITY_ERROR,   ERROR_COMMON_FACILITY, 0x15UL)
#define ERROR_VLAN_GETSUPERVLANIDFAILED       ERROR_DEFINE(ERROR_SEVERITY_ERROR,   ERROR_COMMON_FACILITY, 0x16UL)
#define ERROR_VLAN_GETSUPERVLANIFFAILED       ERROR_DEFINE(ERROR_SEVERITY_ERROR,   ERROR_COMMON_FACILITY, 0x17UL)
#define ERROR_INVALID_IP                      ERROR_DEFINE(ERROR_SEVERITY_ERROR,   ERROR_COMMON_FACILITY, 0x18UL)
#define ERROR_INVALID_MAC                     ERROR_DEFINE(ERROR_SEVERITY_ERROR,   ERROR_COMMON_FACILITY, 0x19UL)
#define ERROR_FEATURE_NOT_ENABLED             ERROR_DEFINE(ERROR_SEVERITY_ERROR,   ERROR_COMMON_FACILITY, 0x1AUL)
#define ERROR_VPN_NOTEXIST                    ERROR_DEFINE(ERROR_SEVERITY_ERROR,   ERROR_COMMON_FACILITY, 0x20UL)
#define ERROR_PORT_NOTALLOWVLAN               ERROR_DEFINE(ERROR_SEVERITY_ERROR,   ERROR_COMMON_FACILITY, 0x21UL)
#define ERROR_ENTRY_REACHLIMIT                ERROR_DEFINE(ERROR_SEVERITY_ERROR,   ERROR_COMMON_FACILITY, 0x22UL)
#define ERROR_END_OF_TABLE                    ERROR_DEFINE(ERROR_SEVERITY_ERROR,   ERROR_COMMON_FACILITY, 0x23UL)
#define ERROR_BATCH_COMPLETE                  ERROR_DEFINE(ERROR_SEVERITY_SUCCESS, ERROR_COMMON_FACILITY, 0x24UL)
#define ERROR_PERMISSION_DENY                 ERROR_DEFINE(ERROR_SEVERITY_ERROR,   ERROR_COMMON_FACILITY, 0x25UL)
#define ERROR_VLAN_ENDVLANLESSTHENSTARTVLAN   ERROR_DEFINE(ERROR_SEVERITY_ERROR,   ERROR_COMMON_FACILITY, 0x26UL)
#define ERROR_GROUP_DENY                      ERROR_DEFINE(ERROR_SEVERITY_ERROR,   ERROR_COMMON_FACILITY, 0x27UL)
#define ERROR_GROUP_C                         ERROR_DEFINE(ERROR_SEVERITY_WARNING, ERROR_COMMON_FACILITY, 0x28UL)
#define ERROR_EFECT_BYREBOOT                  ERROR_DEFINE(ERROR_SEVERITY_INFO,    ERROR_COMMON_FACILITY, 0x29UL)
#define ERROR_INVALID_CIPHER_PASSWD           ERROR_DEFINE(ERROR_SEVERITY_WARNING, ERROR_COMMON_FACILITY, 0x2AUL)
#define ERROR_INVALID_CIPHER_KEY              ERROR_DEFINE(ERROR_SEVERITY_WARNING, ERROR_COMMON_FACILITY, 0x2BUL)
#define ERROR_NO_LICENSE                      ERROR_DEFINE(ERROR_SEVERITY_WARNING, ERROR_COMMON_FACILITY, 0x2CUL)
#define ERROR_NO_LICENSE_EXIT                 ERROR_DEFINE(ERROR_SEVERITY_ERROR,   ERROR_COMMON_FACILITY, 0x2DUL)
#define ERROR_MAC_EXIST                       ERROR_DEFINE(ERROR_SEVERITY_ERROR,   ERROR_COMMON_FACILITY, 0x2EUL)
#define ERROR_FEATURE_NOT_CONFIGURED          ERROR_DEFINE(ERROR_SEVERITY_ERROR,   ERROR_COMMON_FACILITY, 0x2FUL)
#define ERROR_PSK_WRONG_COMPOSITION           ERROR_DEFINE(ERROR_SEVERITY_ERROR,   ERROR_COMMON_FACILITY, 0x30UL)
#define ERROR_PSK_WRONG_LENGTH                ERROR_DEFINE(ERROR_SEVERITY_ERROR,   ERROR_COMMON_FACILITY, 0x31UL)
#define ERROR_FEATURE_NOT_READY               ERROR_DEFINE(ERROR_SEVERITY_ERROR,   ERROR_COMMON_FACILITY, 0x32UL)
#define ERROR_RBAC_DENY_SOME_PORTS            ERROR_DEFINE(ERROR_SEVERITY_ERROR,   ERROR_COMMON_FACILITY, 0x33UL)
#define ERROR_RBAC_DENY_SOME_VLAN             ERROR_DEFINE(ERROR_SEVERITY_ERROR,   ERROR_COMMON_FACILITY, 0x34UL)
#define ERROR_MDC_BUSY                        ERROR_DEFINE(ERROR_SEVERITY_WARNING, ERROR_COMMON_FACILITY, 0x35UL)
#define ERROR_CONTEXT_BUSY                    ERROR_DEFINE(ERROR_SEVERITY_WARNING, ERROR_COMMON_FACILITY, 0x36UL)
#define ERROR_CLUSTER_SHUT_DENY               ERROR_DEFINE(ERROR_SEVERITY_WARNING, ERROR_COMMON_FACILITY, 0x37UL)
#define ERROR_GROUP_DENY_IRF                  ERROR_DEFINE(ERROR_SEVERITY_ERROR,   ERROR_COMMON_FACILITY, 0x38UL)
#define ERROR_GROUP_DENY_PEX                  ERROR_DEFINE(ERROR_SEVERITY_ERROR,   ERROR_COMMON_FACILITY, 0x39UL)
#define ERROR_GROUP_DENY_IRFPEX               ERROR_DEFINE(ERROR_SEVERITY_ERROR,   ERROR_COMMON_FACILITY, 0x3aUL)
#define ERROR_NOTPREPROVISIONED               ERROR_DEFINE(ERROR_SEVERITY_ERROR,   ERROR_COMMON_FACILITY, 0x3bUL)
















