--- src/Makefile
+++ src/Makefile
@@ -44,7 +44,6 @@
 
 INCDIRS += -I$(SRCDIR)/../include -I$(SRCDIR)/flow_l3/include -I$(SRCDIR)/l2/include
 
-CFLAGS += -g
 # CFLAGS += -DCONFIG_DPVS_NETIF_DEBUG
 # for dpvs main program.
 CFLAGS += -D __DPVS__ -DDPVS_VERSION=\"$(VERSION_STRING)\" -DDPVS_BUILD_DATE=\"$(DATE_STRING)\"
@@ -71,7 +70,7 @@
 #	CFLAGS += -rdynamic
 # endif
 
-CFLAGS += -g -O0 
+CFLAGS += -O2
 LIBS += -lpthread -lnuma
 
 CFLAGS += $(INCDIRS) $(LIBS) -fgnu89-inline
