#ifndef _MACFWD_H_
#define _MACFWD_H_

/* MAC转发类型的枚举定义 */
typedef enum {
    MACFW_TYPE_VLAN,
    MACFW_TYPE_BRIDGE,
    MACFW_TYPE_inline,
    MACFW_TYPE_BUTT
}MACFW_TYPE_E;

/* MAC转发中二层业务阶段的枚举定义 */
typedef enum{
    MACFW_L2_INPUT_PREVLANCHECK,
    MACFW_L2_INPUT_PREMACLEARNING,
    MACFW_L2_INPUT_AFTERVLANCHECK,
    MACFW_L2_IP_INPUT,
    MACFW_L2_IP_OUTPUT,
    MACFW_L2_IPV6_INPUT,
    MACFW_L2_IPV6_OUTPUT,
    MACFW_L2_VLAN_OUTPUT,
    MACFW_L2_OUTPUT,
    MACFW_L2_BUTT
}MACFW_L2_PHASE_E;

/* MAC转发中IP业务阶段的枚举定义 */
typedef enum{
    MACFW_IP_PRE_ALL,
    MACFW_IP_INPUT,
    MACFW_IP_OUTPUT,
    MACFW_IP_PRE_RELAY,
    MACFW_IP_RELAY_RECEIVE,
    MACFW_IP_BUTT
}MACFW_IP_PHASE_E;

/* MAC转发中IPv6业务阶段的枚举定义 */
typedef enum{
    MACFW_IPV6_PRE_ALL,
    MACFW_IPV6_INPUT,
    MACFW_IPV6_OUTPUT,    
    MACFW_IPV6_PRE_RELAY,
    MACFW_IPV6_RELAY_RECEIVE,
    MACFW_IPV6_BUTT
}MACFW_IPV6_PHASE_E;

/* VLAN规则检查前阶段ID */
typedef enum tagMacfw_InputPreVlanCheck
{
    MACFW_L2_INPUT_PREVLANCHECK_MGROUP,
    MACFW_L2_INPUT_PREVLANCHECK_WSK,
    MACFW_L2_INPUT_PREVLANCHECK_DDOS,
    MACFW_L2_INPUT_PREVLANCHECK_inline,
    MACFW_L2_INPUT_PREVLANCHECK_BUTT
}MACFW_INPUT_PREVLANCHECK_SERVICEID_E;

typedef enum tagMacfw_InputPreMacLearning
{
    MACFW_L2_INPUT_PREMACLEARNING_BRIDGE,
    MACFW_L2_INPUT_PREMACLEARNING_OFP,
    MACFW_L2_INPUT_PREMACLEARNING_BUTT,
}MACFW_INPUT_PREMACLEARNING_SERVICEID_E;

/* VLAN规则检查后阶段ID */
typedef enum tagMacfw_InputAfterVlanCheck
{
    MACFW_L2_INPUT_AFTERVLANCHECK_USERISOLATION,
    MACFW_L2_INPUT_AFTERVLANCHECK_PRIMAP,
    MACFW_L2_INPUT_AFTERVLANCHECK_QOS,
    MACFW_L2_INPUT_AFTERVLANCHECK_DHCPSP,
    MACFW_L2_INPUT_AFTERVLANCHECK_BUTT
}MACFW_INPUT_AFTERVLANCHECK_SERVICEID_E;

/* VLAN广播二层业务阶段ID */
typedef enum tagMacfw_VlanOutputL2
{
    MACFW_L2_VLAN_OUTPUT_USERISOLATION,
    MACFW_L2_VLAN_OUTPUT_BUTT
}MACFW_L2_VLAN_OUTPUT_SERVICEID_E;

/* 出方向二层业务阶段ID */
typedef enum tagMacfw_OutputL2
{
    MACFW_L2_OUTPUT_WLAN_ICMP,
    MACFW_L2_OUTPUT_PORTISO,
    MACFW_L2_OUTPUT_WLAN_SSIDISO,
    MACFW_L2_OUTPUT_USERISOLATION,
    MACFW_L2_OUTPUT_WLAN_CLIENT,    /* Wlan Client Out */
    MACFW_L2_OUTPUT_MGISOLATION,    /* mobility group isolation */
    MACFW_L2_OUTPUT_BUTT
}MACFW_OUTPUT_L2_SERVICEID_E;
typedef enum tagMacfw_InputIpPreAll
{
    MACFW_IP_PRE_ALL_VSYS,
    MACFW_IP_PRE_ALL_ISG,
    MACFW_IP_PRE_ALL_ATKPROXY,
    MACFW_IP_PRE_ALL_BUTT
}MACFW_INPUT_IP_PRE_ALL_SERVICEID_E;

/* 入方向IP三层业务阶段ID */
typedef enum tagMacfw_InputIp
{
    MACFW_IP_INPUT_APPPROXY,
    MACFW_IP_INPUT_BALANCE,
    MACFW_IP_INPUT_IPMAC,
    MACFW_IP_INPUT_TCPREASSEMBLE,
    MACFW_IP_INPUT_ATK,
    MACFW_IP_INPUT_SCD,        /* 异常外联防护项目 */
    MACFW_IP_INPUT_NETSTREAM,
    MACFW_IP_INPUT_STAMGR,
    MACFW_IP_INPUT_WEBREDIRECT,
    MACFW_IP_INPUT_PORTAL,
    MACFW_IP_INPUT_CONNLMT,
    MACFW_IP_INPUT_AUTHORIZE,
    MACFW_IP_INPUT_FILTER,
    MACFW_IP_INPUT_APPSTAT,
    MACFW_IP_INPUT_QOS,
    MACFW_IP_INPUT_PMM,
    MACFW_IP_INPUT_UCC,
    MACFW_IP_INPUT_WALNVOIP, /* 语音优化 */
    MACFW_IP_INPUT_DNS,
    MACFW_IP_INPUT_BUTT
}MACFW_INPUT_IP_SERVICEID_E;

/* 出方向IP三层业务阶段ID */
typedef enum tagMacfw_OutputIp
{
    MACFW_IP_OUTPUT_INTERZONE,    
    MACFW_IP_OUTPUT_PORTAL,
    MACFW_IP_OUTPUT_FILTER,
    MACFW_IP_OUTPUT_AUTHORIZE,
    MACFW_IP_OUTPUT_ATK,    
    MACFW_IP_OUTPUT_CONNLMT,
    MACFW_IP_OUTPUT_UDPI,
    MACFW_IP_OUTPUT_APPL7,
    MACFW_IP_OUTPUT_APPPROXY,    
    MACFW_IP_OUTPUT_APPSTAT,
    MACFW_IP_OUTPUT_QOS,
    MACFW_IP_OUTPUT_NETSTREAM,
    MACFW_IP_OUTPUT_NETSESSION,    
    MACFW_IP_OUTPUT_UCC,
    MACFW_IP_OUTPUT_WALNVOIP,    /* 语音优化出方向 */
    MACFW_IP_OUTPUT_BUTT
}MACFW_OUTPUT_IP_SERVICEID_E;
typedef enum tagMacfw_InputIpv6PreAll
{
    MACFW_IPV6_PRE_ALL_VSYS,
    MACFW_IPV6_PRE_ALL_ISG,
    MACFW_IPV6_PRE_ALL_ATKPROXY,
    MACFW_IPV6_PRE_ALL_BUTT
}MACFW_INPUT_IPV6_PRE_ALL_SERVICEID_E;

/* 入方向IPV6三层业务阶段ID */
typedef enum tagMacfw_InputIpv6
{
    MACFW_IPV6_INPUT_APPPROXY,
    MACFW_IPV6_INPUT_BALANCE,
    MACFW_IPV6_INPUT_IPMAC,
    MACFW_IPV6_INPUT_TCPREASSEMBLE,
    MACFW_IPV6_INPUT_ATK,
    MACFW_IPV6_INPUT_NETSTREAM,
    MACFW_IPV6_INPUT_STAMGR,
    MACFW_IPV6_INPUT_WEBREDIRECT,
    MACFW_IPV6_INPUT_PORTAL,
    MACFW_IPV6_INPUT_CONNLMT,
    MACFW_IPV6_INPUT_AUTHORIZE,
    MACFW_IPV6_INPUT_FILTER,
    MACFW_IPV6_INPUT_APPSTAT,
    MACFW_IPV6_INPUT_QOS,
    MACFW_IPV6_INPUT_DNS,
    MACFW_IPV6_INPUT_BUTT
}MACFW_INPUT_IPV6_SERVICEID_E;

/* 出方向IPV6三层业务阶段ID */
typedef enum tagMacfw_OutputIpv6
{
    MACFW_IPV6_OUTPUT_INTERZONE,
    MACFW_IPV6_OUTPUT_PORTAL,
    MACFW_IPV6_OUTPUT_FILTER,
    MACFW_IPV6_OUTPUT_AUTHORIZE,
    MACFW_IPV6_OUTPUT_ATK,
    MACFW_IPV6_OUTPUT_CONNLMT,
    MACFW_IPV6_OUTPUT_UDPI,          /* 做用户态DPI业务 */
    MACFW_IPV6_OUTPUT_APPL7,         /* DIM的业务 */
    MACFW_IPV6_OUTPUT_APPPROXY,
    MACFW_IPV6_OUTPUT_APPSTAT,
    MACFW_IPV6_OUTPUT_QOS,
    MACFW_IPV6_OUTPUT_NETSTREAM,
    MACFW_IPV6_OUTPUT_NETSESSION,
    MACFW_IPV6_OUTPUT_BUTT
}MACFW_OUTPUT_IPV6_SERVICEID_E;

/* IP报文透传前阶段 */
typedef enum tagMacfw_IPPreRelay
{
    MACFW_IP_PRE_RELAY_INTERZONE,    /* 域间处理阶段 */
    MACFW_IP_PRE_RELAY_CONNLMT,
    MACFW_IP_PRE_RELAY_BUTT
}MACFW_IP_PRE_RELAY_SERVICEID_E;

/* IP报文透传接收阶段 */
typedef enum tagMacfw_IPRelayReceive
{
    MACFW_IP_RELAY_RECEIVE_INTERZONE,  /* 域间处理阶段 */
    MACFW_IP_RELAY_RECEIVE_BUTT
}MACFW_IP_RELAY_RECEIVE_SERVICEID_E;

/* IPv6报文透传前阶段 */
typedef enum tagMacfw_IPv6PreRelayServiceId
{
    MACFW_IPV6_PRE_RELAY_INTERZONE,   /* 域间处理阶段 */
    MACFW_IPV6_PRE_RELAY_CONNLMT,
    MACFW_IPV6_PRE_RELAY_BUTT
}MACFW_IPV6_PRE_RELAY_SERVICEID_E;

/* IPv6报文透传接收阶段 */
typedef enum tagMacfw_IPv6RelayReceiveServiceId
{
    MACFW_IPV6_RELAY_RECEIVE_INTERZONE,   /* 域间处理阶段 */
    MACFW_IPV6_RELAY_RECEIVE_BUTT
}MACFW_IPV6_RELAY_RECEIVE_SERVICEID_E;

/* 二层上三层IP入方向业务阶段的枚举定义 */
typedef enum tagMacfw_L2IPInput
{
    MACFW_L2_IP_INPUT_ISG,
    MACFW_L2_IP_INPUT_ATK,
    MACFW_L2_IP_INPUT_STAMGR,    
    MACFW_L2_IP_INPUT_WEBREDIRECT,
    MACFW_L2_IP_INPUT_PORTAL,
    MACFW_L2_IP_INPUT_FILTER,
    MACFW_L2_IP_INPUT_QOS,
    MACFW_L2_IP_INPUT_PMM,
    MACFW_L2_IP_INPUT_WLANVOIP,  /* 语音优化 */
    MACFW_L2_IP_INPUT_BUTT
}MACFW_L2_IP_INPUT_SERVICEID_E;

/* 三层下二层IP出方向业务阶段枚举定义 */
typedef enum tagMacfw_L2IPOutput
{
    MACFW_L2_IP_OUTPUT_LANACCESS,
    MACFW_L2_IP_OUTPUT_PORTAL,
    MACFW_L2_IP_OUTPUT_FILTER,
    MACFW_L2_IP_OUTPUT_ATK,
    MACFW_L2_IP_OUTPUT_QOS,
    MACFW_L2_IP_OUTPUT_UCC,
    MACFW_L2_IP_OUTPUT_WLANVOIP,  /* 语音优化 */
    MACFW_L2_IP_OUTPUT_BUTT
}MACFW_L2_OUTPUT_SERVICEID_E;

/* 二层上三层IPv6入方向业务阶段枚举定义 */
typedef enum tagMacfw_L2IPv6Input
{
    MACFW_L2_IPV6_INPUT_ISG,
    MACFW_L2_IPV6_INPUT_ATK,
    MACFW_L2_IPV6_INPUT_STAMGR,
    MACFW_L2_IPV6_INPUT_WEBREDIRECT,
    MACFW_L2_IPV6_INPUT_PORTAL,
    MACFW_L2_IPV6_INPUT_FILTER,
    MACFW_L2_IPV6_INPUT_QOS,
    MACFW_L2_IPV6_INPUT_BUTT
}MACFW_L2_IPV6_INPUT_SERVICEID_E;

/* 三层下二层IPv6出方向业务阶段枚举定义 */
typedef enum tagMacfw_L2IPv6Output
{
    MACFW_L2_IPV6_OUTPUT_LANACCESS,
    MACFW_L2_IPV6_OUTPUT_PORTAL,    
    MACFW_L2_IPV6_OUTPUT_FILTER,    
    MACFW_L2_IPV6_OUTPUT_ATK,    
    MACFW_L2_IPV6_OUTPUT_QOS,    
    MACFW_L2_IPV6_OUTPUT_BUTT
}MACFW_L2_IPV6_OUTPUT_SERVICEID_E;

/* 用于标识二层协议报文的动作状态 */
typedef enum tagMACFW_MAC_PROACTION
{
    MACFW_MAC_PROACTION_DROP = 0,           /* 丢弃 */
    MACFW_MAC_PROACTION_BROADCAST,          /* vlan内广播 */
    MACFW_MAC_PROACTION_UPCPU,              /* 上送 */
    MACFW_MAC_PROACTION_UPCPU_BROADCAST,    /* 上送并且在vlan内广播 */
    MACFW_MAC_PROACTION_CONTINUE,           /* 继续处理 */
    MACFW_MAC_PROACTION_MAX
}MACFW_MAC_PROACTION_E;

/* MAC转发业务处理类型的枚举定义 */
typedef enum
{
    MACFW_SERVICE_L2,
    MACFW_SERVICE_IP,
    MACFW_SERVICE_IPV6,
    MACFW_SERVICE_BUTT
}MACFW_SERVICE_E;

#endif